[package]
name = "ratatui-json-editor"
version = "0.1.0"
edition = "2024"

[dependencies]
fmt = "0.1.0"
ratatui = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tui-textarea = { version = "*", features = ["search"] }
